import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";
import './_globals/globals.scss';
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700" ],
  variable: "--font1",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
